# Generated by Django 4.1.4 on 2022-12-22 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_alter_somos_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='somos',
            name='categorias',
            field=models.ManyToManyField(related_name='somos', to='Blog.categorias'),
        ),
    ]
