# Generated by Django 4.1.4 on 2022-12-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_somos_categorias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('contenido', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='img/tarjetas')),
                ('categorias', models.ManyToManyField(related_name='tarjetas', to='Blog.categorias')),
            ],
        ),
        migrations.CreateModel(
            name='tarjetas2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('contenido', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='img/tarjetas2')),
                ('publicado', models.DateTimeField(blank=True, null=True)),
                ('categorias', models.ManyToManyField(related_name='tarjetas2', to='Blog.categorias')),
            ],
        ),
        migrations.DeleteModel(
            name='Somos',
        ),
    ]
