# Generated by Django 4.1.4 on 2022-12-22 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_tarjetas_tarjetas2_delete_somos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tarjetas2',
        ),
    ]
