# Generated by Django 4.1.4 on 2022-12-22 15:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_delete_tarjetas2'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjetas',
            name='creado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
