# Generated by Django 4.1.4 on 2022-12-22 18:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_tarjetas_creado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('contenido', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='img/trabajos')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('categorias', models.ManyToManyField(related_name='trabajos', to='Blog.categorias')),
            ],
        ),
        migrations.CreateModel(
            name='Nosotrosindex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(max_length=450)),
                ('categorias', models.ManyToManyField(related_name='NosotrosIndex', to='Blog.categorias')),
            ],
        ),
    ]
