# Generated by Django 4.1.4 on 2022-12-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_trabajos_nosotrosindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(max_length=5000)),
                ('categorias', models.ManyToManyField(related_name='NosotrosIndex', to='Blog.categorias')),
                ('creado', models.ManyToManyField(related_name='infoindex', to='Blog.categorias')),
            ],
        ),
        migrations.DeleteModel(
            name='Nosotrosindex',
        ),
    ]
