# Generated by Django 4.1.4 on 2022-12-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_infoindex_delete_nosotrosindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='img/images')),
            ],
        ),
        migrations.AlterField(
            model_name='noticias',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img/images'),
        ),
        migrations.AlterField(
            model_name='tarjetas',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img/images'),
        ),
        migrations.AlterField(
            model_name='trabajos',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img/images'),
        ),
    ]
